"""empty message

Revision ID: 50166da7d394
Revises: ed7af21467c5
Create Date: 2022-05-11 17:55:23.157870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50166da7d394'
down_revision = 'ed7af21467c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downvotes', 'downvote')
    op.drop_column('upvotes', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('downvotes', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
