"""empty message

Revision ID: 66681b2b1198
Revises: 9db5ea8d0892
Create Date: 2022-05-11 10:48:35.305369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66681b2b1198'
down_revision = '9db5ea8d0892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.alter_column('pitches', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
